name: "macOS CI"
on:
  push:
    branches: [blueprint]
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: vicr123/libcontemporary/brew-universalinstall@actions
        name: "Install Dependencies"
        with:
          packages: "qt:libgit2:cmake:ninja"
      - uses: vicr123/libcontemporary/install-libcontemporary@actions
      - uses: vicr123/libcontemporary/build-project@actions
        name: "Build ttexteditor"
        with:
          project: "vicr123/ttexteditor"
          commitish: "master"
      - uses: vicr123/libcontemporary/build-project@actions
        name: "Build contemporary-theme"
        with:
          project: "vicr123/contemporary-theme"
          commitish: "blueprint"
      - uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - uses: vicr123/libcontemporary/build-project@actions
        name: "Build project"
        with:
          project: "."
      - uses: vicr123/libcontemporary/deploy-project@actions
        id: deploy
        name: "Deploy project"
        with:
          subdir: "application"
      - uses: actions/upload-artifact@v1
        name: Upload Artifact to GitHub Actions
        with:
          name: "theBranch-macOS"
          path: ${{ steps.deploy.outputs.package }}
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@v3
        name: "Download Artifact"
        id: download
        with:
          name: "theBranch-macOS"
      - name: "Upload to Release"
        uses: softprops/action-gh-release@v1
        with:
          files: "*.dmg"
